name: decision-transformer-gym
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pytorch
  - cudatoolkit
  - pip:
      - gym
      - gymnasium
      - mujoco
      - torch
      - transformers
      - wandb
      - minari
      - imageio